#! /bin/sh

bspc config border_width        1
bspc config window_gap          20
bspc config top_padding         0
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	false
bspc config pointer_follows_focus 	false
bspc config click_to_focus          true	
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true

bspc config normal_border_color "#131313"
bspc config focused_border_color "#3068AC"
bspc config presel_feedback_color "#3068AC"

bspc monitor eDP1 -n 1 -d term web code mail music other
bspc monitor DP1 -n 2 -d 1 2 3

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating

sxhkd &
feh --bg-scale ~/Pictures/wallpaper.jpg &
$HOME/.config/polybar/start.sh &
compton --config "$HOME/.config/compton/compton.conf" -b &
