#! /bin/sh

bspc config border_width        1
bspc config window_gap          20
bspc config top_padding         0
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_follows_focus 	false
bspc config click_to_focus          true	
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true

bspc config normal_border_color '#282a36'
bspc config focused_border_color '#527fc1'
bspc config presel_feedback_color '#ffac8d'

MONITORS=$(xrandr -q| grep " connected" | wc -l)

if [ $MONITORS = '2']; then
    bspc monitor eDP1 -n eDP1 -d term web notes mail music other
    bspc monitor DP1 -n DP1 -d code chrome other other other

    bspc rule -a Firefox desktop=^2 follow=on
    bspc rule -a Code desktop=^7 follow=on
    bspc rule -a Thunderbird desktop=^4 follow=on
    bspc rule -a Chromium-browser desktop=^8 follow=on
    bspc rule -a Simplenote desktop=^3 follow=on
    bspc rule -a Spotify desktop=^5 follow=on
elif [ $MONITORS = '1']; then
    bspc monitor eDP1 -n eDP1 -d term web chrome code notes mail music other

    bspc rule -a Firefox desktop=^2 follow=on
    bspc rule -a Code desktop=^4 follow=on
    bspc rule -a Thunderbird desktop=^6 follow=on
    bspc rule -a Chromium-browser desktop=^3 follow=on
    bspc rule -a Simplenote desktop=^5 follow=on
    bspc rule -a Spotify desktop=^7 follow=on
fi

sxhkd &
dunst &
feh --bg-scale ~/Pictures/wallpaper.jpg &
$HOME/.config/polybar/start.sh &
compton --config "$HOME/.config/compton/compton.conf" -b &
